CREATE DATABASE DB_DA2_ADB1_14
GO
USE DB_DA2_ADB1_14

--drop database DB_DA2_ADB1_14
--go

CREATE TABLE KHACHHANG
(
	MAKH CHAR(8),
	HOTEN NVARCHAR(60),
	SDT CHAR(10),
	EMAIL VARCHAR(50),
	GIOITINH CHAR(1),
	NGSINH DATE,
	SONHA VARCHAR(20),
	DUONG NVARCHAR(50),
	PHUONG NVARCHAR(30),
	QUAN NVARCHAR(20),
	TINH NVARCHAR(20),
	MATKHAU VARCHAR(20)
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH)
)

CREATE TABLE DONHANG
(
    MADH CHAR(8),
	MANV CHAR(4),
    MAKH CHAR(8),
	MAHT CHAR(4),
	MAGH CHAR (4),
	DIACHI NVARCHAR(100),
	SDT CHAR(10),
	NGUOINHAN NVARCHAR(20),
    NGAYLAP DATE,
	TINHTRANG NVARCHAR(10),
	PHIVC DECIMAL(19,4), 
    TONGTIEN DECIMAL(19,4),
    CONSTRAINT PK_DONHANG PRIMARY KEY (MADH)
)

CREATE TABLE CT_DONHANG
(
    MADH CHAR(8),
    MASP CHAR(8),
    SLDAT INT,
    DONGIA DECIMAL(19,4),
    PTGIAM FLOAT,
    CONSTRAINT PK_CTHD PRIMARY KEY (MADH,MASP)
)

CREATE TABLE HINHTHUCTT
(
    MAHT CHAR(4),
    TENHT NVARCHAR(20) NOT NULL
    CONSTRAINT PK_HTTT PRIMARY KEY (MAHT)
)

CREATE TABLE THUONGHIEU
(
    MATH CHAR(4),
    TENTH NVARCHAR (30),
    XUATXU NVARCHAR(20)
    CONSTRAINT PK_THUONGHIEU PRIMARY KEY (MATH)
)

CREATE TABLE HINHTHUCGH
(
    MAGH CHAR(4),
    TENGH NVARCHAR(20) NOT NULL
    CONSTRAINT PK_HTGH PRIMARY KEY (MAGH)
)
CREATE TABLE DOTUOI
(
    MATUOI CHAR(4),
    MOTA NVARCHAR(20) NOT NULL
    CONSTRAINT PK_DOTUOI PRIMARY KEY (MATUOI)
)

CREATE TABLE LOAISP 
(
	MALOAISP CHAR(4), 
	TENLOAISP NVARCHAR (30) NOT NULL,  
	LOAISP_CHA1 CHAR(4),
	LOAISP_CHA2 CHAR(4)
	CONSTRAINT PK_LOAISP PRIMARY KEY (MALOAISP)
)

CREATE TABLE SANPHAM 
(
	MASP CHAR(8), 
	MALOAISP CHAR (4) NOT NULL, 
	MATUOI CHAR (4) NOT NULL , 
	MATH CHAR (4) NOT NULL,
	TENSP NVARCHAR (30) NOT NULL,
	GIABAN DECIMAL(19,4) NOT NULL,
	MOTA NVARCHAR(50) NOT NULL,
	TRONGLUONG INT NOT NULL
	CONSTRAINT PK_SANPHAM PRIMARY KEY (MASP)
)

CREATE TABLE NHANVIEN 
(
	MANV CHAR(4), 
	MALOAINV CHAR(4)  NOT NULL, 
	MADV CHAR (4), 
	HOTEN NVARCHAR (60) NOT NULL,  
	SDT CHAR (10) NOT NULL, 
	GIOITINH CHAR(1),
	NGAYSINH DATE, 
	LUONG DECIMAL(19,4) NOT NULL,
	TENLOAINV NVARCHAR(20) NOT NULL
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
)

CREATE TABLE KHOHANG 
(
	MAKHO CHAR(4),
	MANV CHAR (4) NOT NULL,
	DIACHI NVARCHAR (100) NOT NULL
	CONSTRAINT PK_KHO PRIMARY KEY (MAKHO)
)

CREATE TABLE DVVC 
(
	MADV CHAR(4), 
	TENDV NVARCHAR (20) NOT NULL
	CONSTRAINT PK_DVVC PRIMARY KEY (MADV)
)

CREATE TABLE NHAPHANG 
(
	MANH CHAR(8), 
	MAKHO CHAR(4) NOT NULL,  
	MANV CHAR(4) NOT NULL, 
	NGAYLAP DATE
	CONSTRAINT PK_NHAPHANG PRIMARY KEY (MANH)
)

CREATE TABLE CT_KHO
(
	MAKHO CHAR(4), 
	MASP CHAR(8),  
	SOLUONG INT NOT NULL, 
	CONSTRAINT PK_CT_KHO PRIMARY KEY (MAKHO, MASP)
)

CREATE TABLE CT_NHAPHANG 
(
	MANH CHAR(8), 
	MASP CHAR(8),  
	SLNHAP CHAR(4) NOT NULL, 
	DONGIA DECIMAL(19,4) NOT NULL
	CONSTRAINT PK_CT_NHAPHANG PRIMARY KEY (MANH, MASP)
)

ALTER TABLE NHAPHANG 
ADD
CONSTRAINT FK_NHAPHANG_KHOHANG FOREIGN KEY (MAKHO) REFERENCES KHOHANG(MAKHO)

ALTER TABLE NHAPHANG 
ADD
CONSTRAINT FK_NHAPHANG_NHANVIEN  FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE CT_DONHANG
ADD 
CONSTRAINT FK_CTDH_DONHANG FOREIGN KEY (MADH) REFERENCES DONHANG(MADH),
CONSTRAINT FK_CTDH_SANPHAM FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)

ALTER TABLE CT_NHAPHANG
ADD 
CONSTRAINT FK_CTNH_NHAPHANG FOREIGN KEY (MANH) REFERENCES NHAPHANG(MANH),
CONSTRAINT FK_CTNH_SANPHAM FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)

ALTER TABLE CT_KHO
ADD 
CONSTRAINT FK_CTKHO_KHOHANG FOREIGN KEY (MAKHO) REFERENCES KHOHANG(MAKHO),
CONSTRAINT FK_CTKHO_SANPHAM FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)

ALTER TABLE DONHANG
ADD 
CONSTRAINT FK_DONHANG_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV), 
CONSTRAINT FK_DONHANG_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH), 
CONSTRAINT FK_DONHANG_HINHTHUCTT FOREIGN KEY (MAHT) REFERENCES HINHTHUCTT(MAHT), 
CONSTRAINT FK_DONHANG_HINHTHUCGH FOREIGN KEY (MAGH) REFERENCES HINHTHUCGH(MAGH)

ALTER TABLE NHANVIEN
ADD 
CONSTRAINT FK_NHANVIEN_DVVC FOREIGN KEY (MADV) REFERENCES DVVC(MADV)

ALTER TABLE SANPHAM 
ADD
CONSTRAINT FK_SANPHAM_LOAISP FOREIGN KEY (MALOAISP) REFERENCES LOAISP(MALOAISP), 
CONSTRAINT FK_SANPHAM_DOTUOI FOREIGN KEY (MATUOI) REFERENCES DOTUOI(MATUOI), 
CONSTRAINT FK_SANPHAM_THUONGHIEU FOREIGN KEY (MATH) REFERENCES THUONGHIEU(MATH)

ALTER TABLE LOAISP
ADD 
CONSTRAINT FK_LOAISP_LOAISPCHA1 FOREIGN KEY (LOAISP_CHA1) REFERENCES LOAISP(MALOAISP),
CONSTRAINT FK_LOAISP_LOAISPCHA2 FOREIGN KEY (LOAISP_CHA2) REFERENCES LOAISP(MALOAISP)
